kind: Secret
apiVersion: v1
metadata:
    name: edge-proxy-certs
    namespace: edge-proxy
stringData:
    ostrava.openstack.cloud.dev.crt: ENC[AES256_GCM,data:veS6,iv:N50dFOnfdgEn2jIxUAPfnC8oGHdtYKP4rrlxb+2TPqY=,tag:hbYlcEWNUmFRd2f6fRTPeQ==,type:str]
    ostrava.openstack.cloud.dev.key: ENC[AES256_GCM,data:9f8u,iv:WvDK2lKFDTcayc0pcuBevpQMXKeD05dA+kaKHi5UkK0=,tag:eRuOkcnanORUQdcv6XL2tA==,type:str]
    wildcard.ostrava.openstack.cloud.dev.crt: ENC[AES256_GCM,data:kqOt,iv:i7d0VTfWF5/JWDKsARM22Y+CBGG/gAG2utoMBclzxTg=,tag:fKIei7gU8d3Ddp+of9edow==,type:str]
    wildcard.ostrava.openstack.cloud.dev.key: ENC[AES256_GCM,data:/szI,iv:3rIjOGUcpa+vKPJ/4NH2snboJYNsHbXM/U7pHSrt9KY=,tag:LHVTf2RhV4E+YvSn3uw2vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv9468v9dcmzxksl4cmnny9pw679zh29cvc5u9fl42g6s0f4h9cq8yjzx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQUNXb3cxYUdhdHRZRzJs
            ZVQzWTlCZUhPNk1pU1lhckZCYUQ3TnF1QzJrCjg5ZG56S2xJUWVLdE5DdE50dDJD
            R0t0YVlwLzRmTFAvenFtTkZjdHh6b2MKLS0tIC8wMmIrc0dmZlNzTmF5cXFHTStq
            eDA1bDZaRDV2S2tkaTRoeTlUYVBxczgKOxST9leQCL7s0FOCS97fAm5IAzOCqpO6
            PkOtQT1AQREFZzdPFWtQAvRCIEVA9c5GaiK76rYyzOVzC526Rrfmeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T08:33:17Z"
    mac: ENC[AES256_GCM,data:/n6fhnt/2MoXrgwuDmmPk0/uUKrhn8fgI3kCc/HE8BgjlIXsZldI67erM1Sh/aTLtrOL638zxOZdjwtBW3phF2MoW+9SoSAZDPIJvgBTnGJz2thfxFGBSoFJA+o6zBafQ64Zh64W+0bEzx+l+RgPKtO5rTNpYa65lJUvwY9VyxM=,iv:ah9Oe2xxS2J2+QFNuIizzJiHRpb0gxvJBMZsfQ/uCMg=,tag:NBT+JbkyN1aL48HFADmRfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
