# Example of plain secret structure, avoid pushing plain secrets into Git, pre-commit hook / CI test needed
apiVersion: v1
kind: Secret
metadata:
  name: common
  namespace: openstack
type: Opaque
stringData:
  barbican.identity.barbican.password: '********************'
  barbican.oslo_db.barbican.password: '********************'
  barbican.oslo_messaging.barbican.password: '********************'
  cinder.identity.cinder.password: '********************'
  cinder.identity.test.password: '********************'
  cinder.oslo_db.cinder.password: '********************'
  cinder.oslo_messaging.cinder.password: '********************'
  glance.identity.glance.password: '********************'
  glance.identity.test.password: '********************'
  glance.oslo_db.glance.password: '********************'
  glance.oslo_messaging.glance.password: '********************'
  heat.identity.heat.password: '********************'
  heat.identity.heat_stack_user.password: '********************'
  heat.identity.heat_trustee.password: '********************'
  heat.identity.test.password: '********************'
  heat.oslo_db.heat.password: '********************'
  heat.oslo_messaging.heat.password: '********************'
  keystone.identity.admin.password: '********************'
  keystone.identity.test.password: '********************'
  keystone.oslo_cache.memcache_secret_key: '********************'
  keystone.oslo_db.keystone.password: '********************'
  keystone.oslo_messaging.keystone.password: '********************'
  mariadb.admin.password: '********************'
  mariadb.exporter.password: '********************'
  mariadb.sst.password: '********************'
  neutron.identity.test.password: '********************'
  neutron.oslo_db.neutron.password: '********************'
  neutron.oslo_messaging.neutron.password: '********************'
  nova.conf.neutron.metadata_proxy_shared_secret: '********************'
  nova.identity.neutron.password: '********************'
  nova.identity.nova.password: '********************'
  nova.identity.placement.password: '********************'
  nova.identity.test.password: '********************'
  nova.network.ssh.private_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ***********************************
    -----END OPENSSH PRIVATE KEY-----
  nova.network.ssh.public_key: |
    ssh-rsa **************************************** nova-ssh@g2-oidc
  nova.oslo_db.nova.password: '********************'
  nova.oslo_messaging.nova.password: '********************'
  prometheus_exporter_openstack.identity.user.password: '********************'
  rabbitmq.admin.password: '********************'
  radosgw.identity.swift.password: '********************'
