kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: ingress-controller
  namespace: openstack
spec:
  interval: 5m
  dependsOn: []
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  # https://github.com/beskar-cloud/openstack-helm-infra/blob/main/ingress/values.yaml
  values:
    images:
      tags:
        entrypoint: &kubernetes-entrypoint-image quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        ingress: k8s.gcr.io/ingress-nginx/controller:v1.1.3
        ingress_module_init: &neutron-image docker.io/openstackhelm/neutron:yoga-ubuntu_focal-20230526
        ingress_routed_vip: *neutron-image
        error_pages: k8s.gcr.io/defaultbackend:1.4
        keepalived: docker.io/osixia/keepalived:1.4.5
        dep_check: *kubernetes-entrypoint-image
    release_uuid: ${RELEASE_UUID}
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      error_server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        error_page: 2
        ingress: 2
