kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: memcached
  namespace: &ns openstack
spec:
  interval: 5m
  dependsOn:
  - name: "mariadb"
    namespace: *ns
  targetNamespace: *ns
  storageNamespace: *ns
  chart:
    spec:
      chart: memcached
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  # https://github.com/beskar-cloud/openstack-helm-infra/blob/main/memcached/values.yaml
  values:
    images:
      pull_policy: Always
      tags:
        dep_check: 'quay.io/airshipit/kubernetes-entrypoint:v1.0.0'
        memcached: 'docker.io/library/memcached:1.6.20'
        prometheus_memcached_exporter: 'docker.io/prom/memcached-exporter:v0.11.3'
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_memcached_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    monitoring:
      prometheus:
        enabled: true
