apiVersion: v1
kind: Secret
metadata:
    name: keystone-apache-oidc-metadata
    namespace: openstack
type: Opaque
stringData:
    oidc_api_client_id: ENC[AES256_GCM,data:DIgHk2eUUK5l+0GkePlRLne7ej++5+LQym/1EoBLKU9YDw1m,iv:eKMSiv9HtKmQ2WgG6fxQ8z6L3/wITMQ4XsdStueNyYY=,tag:aTYp/U6LMqODvvWwS5iVmw==,type:str]
    oidc_api_client_secret: ENC[AES256_GCM,data:T6ahjOWMjVD3ulMjW0w1uaBzSa9wlt9bCdtfETsG6LkUY/aG9RK7xtGowTtdnzwlZ0evkPT67mY9Edo9rj/vD9idUsYzGu41,iv:gpwXTmZmyXByQE+HLY0fMpYAm07QSKfYLZtdDk4a8B0=,tag:3BDBvLq8JPq2zTiIoD4nRg==,type:str]
    oidc_crypto_passphrase: ENC[AES256_GCM,data:PxyWfzSyjp18GUV1etSqvT7TcLghm61MaqmTVbXp+No=,iv:0CwXHFPOSRdVDajYR2c55flPjxxFX2nwdjbrql+OPHw=,tag:nd+YMeZVdm8DaetbtUb22w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv9468v9dcmzxksl4cmnny9pw679zh29cvc5u9fl42g6s0f4h9cq8yjzx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWHZnTjZQQ0QvR05zMVRK
            V0dPY2FIUUR6SXVYQ2NMcXlqLzdjMEpjZkdBCndUTXdvVE1tc3NqSHhQZnkyT1ZH
            Z2dUSTJaZHB5SmhjWm4vazRtYVJscEUKLS0tIFJ4STRrakk0RXJ2S21uRE92eENz
            dG9pc2VZSmtZdzRia3QvNTQ4aTk0WUUKt08HszTQLCc390xFYd+T5sQPwEdw5I/Y
            y+wOSt5bweKd6TUMLG+IO6ZsJJ4raTl+lidZH5pimpUlVhUupaWDkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T09:20:26Z"
    mac: ENC[AES256_GCM,data:O7RnJmGMF3OxTHkT1l6XU/oBq4S+GQHBScHIwBbJLAwhOZNhpD3Gf3qkzoCzoADlD02IsrlstDzDVkI4eSdEVsG4tolEr01Z1P5gTYmDVeuZLumdtg38ta3WpwXqzqEsWXCDVIluL+9gOVtPWKRPiFZDZn3ATbadH1NAah9hUMI=,iv:1cLrxrOC9sC9xfvJ2ojQuERuVZ/BcUHAS+MK/KYQii0=,tag:p6D7y21/+9eV3FjQQ2W6aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
