kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: libvirt
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "cinder"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: libvirt
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: common
    valuesKey: cinder.conf.backends.du-ceph-cl3.rbd_secret_uuid
    targetPath: conf.ceph.cinder.secret_uuid
  - kind: Secret
    name: cinder-volume-rbd-keyring
    valuesKey: key
    targetPath: conf.ceph.cinder.keyring
  # https://github.com/beskar-cloud/openstack-helm-infra/blob/main/libvirt/values.yaml
  values:
    images:
      tags:
        libvirt: docker.io/openstackhelm/libvirt:yoga-focal-20230415
        ceph_config_helper: docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_17.2.6-1-20230508
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
      pull_policy: Always
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      libvirt:
        listen_tcp: "1"
        listen_tls: "0"
        auth_tcp: "none"
        ca_file: ""
        listen_addr: "0.0.0.0"
        log_level: "3"
        log_outputs: "1:file:/var/log/libvirt/libvirtd.log"
      ceph:
        cinder:
          # client.cinder.it4i userID and keyring
          user: "cinder.it4i"       # expands to client.*
          # keyring: ""             # secret/openstack/cinder-volume-rbd-keyring/key
          # secret_uuid: ""         # configmap/openstack/common/cinder.conf.backends.du-ceph-cl3.rbd_secret_uuid
    pod:
      libvirt_wrapper: "bin/_libvirt-cg1-jammy.sh.tpl"
