kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: ingress-kube-system
  namespace: kube-system 
spec:
  interval: 5m
  #dependsOn:
  #- name: "helm-toolkit"
  #  namespace: "default"
  targetNamespace: kube-system 
  storageNamespace: kube-system
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default
      interval: 1m
  values:
    images:
      tags:
        entrypoint: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        #ingress: docker.itera.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0
        ingress: k8s.gcr.io/ingress-nginx/controller:v1.1.3
        ingress_module_init: docker.itera.io/openstackhelm/neutron:latest-ussuri-ubuntu_bionic
        ingress_routed_vip: docker.itera.io/openstackhelm/neutron:latest-ussuri-ubuntu_bionic
        error_pages: docker.itera.io/google_containers/defaultbackend:1.4
        keepalived: docker.itera.io/osixia/keepalived:1.4.5
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.itera.io/docker:17.07.0
    release_uuid: 8ca1081d-f2b1-4494-aa0b-b14496e132f8
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      error_server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        error_page: 2
    deployment:
      mode: cluster
      type: DaemonSet
    network:
      host_namespace: true
