# calico-node service for calico-node/felix prometheus metrics service discovery
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    k8s-app: calico-node
  name: calico-node
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: calico-node
  type: ClusterIP
