kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: mariadb
  namespace: &ns osh-infra
spec:
  interval: 5m
  targetNamespace: *ns
  storageNamespace: *ns
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  valuesFrom:
  - kind: Secret
    name: common
    valuesKey: mariadb.admin.password
    targetPath: endpoints.oslo_db.auth.admin.password
  - kind: Secret
    name: common
    valuesKey: mariadb.exporter.password
    targetPath: endpoints.oslo_db.auth.exporter.password
  - kind: Secret
    name: common
    valuesKey: mariadb.sst.password
    targetPath: endpoints.oslo_db.auth.sst.password
  values:
    images:
      tags:
        mariadb: &mariadb-image docker.io/openstackhelm/mariadb:ubuntu_focal-20230415
        ingress: k8s.gcr.io/ingress-nginx/controller:v1.5.2
        error_pages: k8s.gcr.io/defaultbackend:1.4
        prometheus_create_mysql_user: *mariadb-image
        prometheus_mysql_exporter: docker.io/prom/mysqld-exporter:v0.12.1
        prometheus_mysql_exporter_helm_tests: &heat-image docker.io/openstackhelm/heat:yoga-ubuntu_focal-20230526
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        mariadb_backup: quay.io/airshipit/porthole-mysqlclient-utility:latest-ubuntu_bionic
        ks_user: *heat-image
        scripted_test: *mariadb-image
    endpoints:
      oslo_db:
        auth:
          admin: {}
          #  password: secret/common/mariadb.admin.password
          exporter: {}
          #  password: secret/common/mariadb.exporter.password
          sst: {}
          #  password: secret/common/mariadb.sst.password
    volume:
      class_name: external-ceph-rbd-cloud-ceph-blockpool-it4i
      backup:
        class_name: external-ceph-rbd-cloud-ceph-blockpool-it4i-backup
