apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pushgateway
  namespace: &ns osh-infra
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
      interval: 5m
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/values.yaml
  values:
    fullnameOverride: pushgateway
    namespaceOverride: *ns
    service:
      type: ClusterIP
      port: 9091
      targetPort: 9091
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 512Mi
