# Example of plain secret structure, avoid pushing plain secrets into Git, CI/prehook test needed
kind: Secret
apiVersion: v1
metadata:
    name: edge-proxy-certs
    namespace: edge-proxy
stringData:
    ostrava.openstack.cloud.dev.crt: "..."
    ostrava.openstack.cloud.dev.key: "..."
    wildcard.ostrava.openstack.cloud.dev.crt: "..."
    wildcard.ostrava.openstack.cloud.dev.key: "..."
