kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: osh-infra-ldap
  namespace: osh-infra
spec:
  interval: 5m
  dependsOn:
  - name: "prometheus-openstack-exporter"
    namespace: "openstack"
  targetNamespace: osh-infra
  storageNamespace: osh-infra
  chart:
    spec:
      chart: ldap
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        bootstrap: "docker.itera.io/osixia/openldap:1.2.0"
        ldap: docker.itera.io/osixia/openldap:1.2.0
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0 
        image_repo_sync: docker.itera.io/docker:17.07.0
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    bootstrap:
      enabled: true
    storage:
      pvc:
        enabled: true
        class_name: ceph-block
