kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: prometheus-alertmanager
  namespace: osh-infra
spec:
  interval: 5m
  dependsOn:
  - name: "prometheus-node-exporter"
    namespace: "osh-infra"
  targetNamespace: osh-infra
  storageNamespace: osh-infra
  chart:
    spec:
      chart: prometheus-alertmanager
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        alertmanager: docker.itera.io/prom/alertmanager:v0.11.0
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0 
        image_repo_sync: docker.itera.io/docker:17.07.0
    network:
      alertmanager:
        node_port:
          enabled: true
          port: 30903
    #pod:
    #  replicas:
    #    alertmanager: 1
    labels:
      alertmanager:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    storage:
      alertmanager:
        storage_class: ceph-block