kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: grafana
  namespace: osh-infra
spec:
  interval: 5m
  dependsOn:
  - name: "prometheus"
    namespace: "osh-infra"
  targetNamespace: osh-infra
  storageNamespace: osh-infra
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        grafana: grafana/grafana:7.3.7-ubuntu
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        db_init: docker.itera.io/openstackhelm/heat:latest-wallaby-ubuntu_bionic
        grafana_db_session_sync: docker.itera.io/openstackhelm/heat:latest-wallaby-ubuntu_bionic
        helm_tests: docker.itera.io/openstackhelm/heat:latest-wallaby-ubuntu_bionic
        image_repo_sync: docker.itera.io/docker:17.07.0
    endpoints:
      monitoring:
        auth:
          admin:
            password: wuaeyfsdhawsIwdihf
      oslo_db:
        namespace: osh-infra
        auth:
          admin:
            password: wuaeyfsdhawsI
          user:
            password: hDH3e6h6aT5x7bnSQDzM
      oslo_db_session:
        namespace: osh-infra
        auth:
          admin:
            password: wuaeyfsdhawsI
          user:
            password: fshieozwq1eduyf
      grafana:
        auth:
          admin:
            password: fshieozwq1qsw
    labels:
      grafana:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
