kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: osh-openstack-ingress-controller
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: rook-ceph-services
    namespace: rook-ceph
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        entrypoint: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        ingress: k8s.gcr.io/ingress-nginx/controller:v1.1.3
        ingress_module_init: docker.io/openstackhelm/neutron:stein-ubuntu_bionic
        ingress_routed_vip: docker.io/openstackhelm/neutron:stein-ubuntu_bionic
        error_pages: k8s.gcr.io/defaultbackend:1.4
        keepalived: docker.io/osixia/keepalived:1.4.5
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.io/library/docker:17.07.0
    release_uuid: ${RELEASE_UUID}
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      error_server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        error_page: 2
        ingress: 2
