kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: mariadb
  namespace: openstack
spec:
  interval: 5m
  timeout: 15m
  dependsOn:
  - name: rook-ceph-services
    namespace: rook-ceph
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    #images:
    #  tags:
    #    mariadb: docker.io/openstackhelm/mariadb:latest-ubuntu_focal
    #    ingress: k8s.gcr.io/ingress-nginx/controller:v1.1.3
    #    error_pages: k8s.gcr.io/defaultbackend:1.4
    #    prometheus_create_mysql_user: docker.io/library/mariadb:10.5.9-focal
    #    prometheus_mysql_exporter: docker.io/prom/mysqld-exporter:v0.12.1
    #    prometheus_mysql_exporter_helm_tests: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
    #    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    #    image_repo_sync: docker.io/library/docker:17.07.0
    #    mariadb_backup: quay.io/airshipit/porthole-mysqlclient-utility:latest-ubuntu_bionic
    #    ks_user: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
    #    scripted_test: docker.io/openstackhelm/mariadb:ubuntu_focal-20210415
    #    #mariadb: docker.itera.io/openstackhelm/mariadb:ubuntu_xenial-20200303
    #    mariadb: docker.io/openstackhelm/mariadb:latest-ubuntu_focal
    #    #ingress: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0 
    #    ingress: k8s.gcr.io/ingress-nginx/controller:v1.1.3
    #    error_pages: docker.itera.io/google_containers/defaultbackend:1.4
    #    #prometheus_create_mysql_user: docker.itera.io/mariadb:10.2.31
    #    prometheus_create_mysql_user: docker.io/library/mariadb:10.5.9-focal
    #    #prometheus_mysql_exporter: docker.itera.io/prom/mysqld-exporter:v0.11.0
    #    prometheus_mysql_exporter: docker.io/prom/mysqld-exporter:v0.12.1
    #    #prometheus_mysql_exporter_helm_tests: docker.itera.io/openstackhelm/heat:newton-ubuntu_xenial
    #    prometheus_mysql_exporter_helm_tests: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
    #    dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
    #    image_repo_sync: docker.itera.io/docker:17.07.0
    #    #mariadb_backup: docker.itera.io/stackanetes/porthole-mysqlclient-utility:latest-ubuntu_bionic
    #    mariadb_backup: quay.io/airshipit/porthole-mysqlclient-utility:latest-ubuntu_bionic
    #    #ks_user: docker.itera.io/openstackhelm/heat:latest-victoria-ubuntu_bionic
    #    ks_user: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
    #    #scripted_test: docker.itera.io/openstackhelm/mariadb:ubuntu_xenial-20191031
    #    scripted_test: docker.io/openstackhelm/mariadb:ubuntu_focal-20210415
    endpoints:
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek
          exporter:
            password: c3Gilft2iZggY9ms8WE0
          sst:
            password: iN1Nqz23qebDHsmMNVIW
    monitoring:
      prometheus:
        enabled: True
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_mysql_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    volume:
      class_name: ceph-block
      backup:
        class_name: ceph-block
