kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: memcached
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "mariadb"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: memcached
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      pull_policy: Always
      tags:
        dep_check: 'quay.io/airshipit/kubernetes-entrypoint:v1.0.0'
        memcached: 'docker.io/library/memcached:1.5.5'
        prometheus_memcached_exporter: docker.io/prom/memcached-exporter:v0.4.1
        image_repo_sync: docker.io/library/docker:17.07.0
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_memcached_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    monitoring:
      prometheus:
        enabled: true
