

kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: rabbitmq
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "memcached"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        prometheus_rabbitmq_exporter: docker.io/kbudde/rabbitmq-exporter:v1.0.0-RC7.1
        prometheus_rabbitmq_exporter_helm_tests: docker.io/openstackhelm/heat:stein-ubuntu_bionic
        #rabbitmq_init: docker.io/openstackhelm/heat:stein-ubuntu_bionic
        rabbitmq_init: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
        rabbitmq: docker.io/library/rabbitmq:3.9.0
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        scripted_test: docker.io/library/rabbitmq:3.9.0-management
        image_repo_sync: docker.io/library/docker:17.07.0
    pod:
      replicas:
        server: 3
        prometheus_rabbitmq_exporter: 1
    endpoints:
      oslo_messaging:
        auth:
          user:
            username: rabbitmq-admin
            password: 5mOMtMEnkx4TxTwEMGqY
    monitoring:
      prometheus:
        enabled: True
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_rabbitmq_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    volume:
      class_name: ceph-block
