kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: keystone
  namespace: openstack
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
  - name: "rabbitmq"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: keystone
      sourceRef:
        kind: GitRepository
        name: openstack-helm
        namespace: default 
      interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    network:
      api:
        node_port:
          enabled: true 
    images:
      tags:
        bootstrap: &heat-image hemsonawane/heat:latest-zed-ubuntu_focal
        test: docker.io/xrally/xrally-openstack:2.0.0
        db_init: *heat-image
        keystone_db_sync: &keystone-image hemsonawane/keystone:latest-zed-ubuntu_focal
        db_drop: *heat-image
        ks_user: *heat-image
        rabbit_init: docker.io/rabbitmq:3.9-management
        keystone_fernet_setup: *keystone-image
        keystone_fernet_rotate: *keystone-image
        keystone_credential_setup: *keystone-image
        keystone_credential_rotate: *keystone-image
        keystone_credential_cleanup: *heat-image
        keystone_api: *keystone-image
        keystone_domain_manage: *keystone-image
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.io/docker:17.07.0
    endpoints:
      identity:
        name: keystone
        namespace: openstack
        auth:
          admin:
            password: grijgfreiefdf
          test:
            password: JoYly5RYLdTgbXwu5NfD
      oslo_cache:
        auth:
          memcache_secret_key: 4hvV8Q8ZBrQbguej4jwj
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek
          keystone:
            password: WYvPEnl6aZ0tQZwWbeVS
      oslo_messaging:
        auth:
          admin:
            username: rabbitmq-admin
            password: 5mOMtMEnkx4TxTwEMGqY
          keystone:
            username: keystone-rabbitmq-user
            password: xoSffj4Xl4HE0zx8aLx8
        statefulset:
          replicas: 3
          name: openstack-rabbitmq-rabbitmq
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        api: 3
