kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: glance
  namespace: openstack
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
  - name: "radosgw-openstack"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: glance
      sourceRef:
        kind: GitRepository
        name: openstack-helm
        namespace: default 
      interval: 1m
  values:
    network:
      api:
        node_port:
          enabled: true 
    images:
      tags:
        test: docker.io/xrally/xrally-openstack:2.0.0
        glance_storage_init: docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_xenial
        glance_metadefs_load: &glance-image hemsonawane/glance:latest-zed-ubuntu_focal
        db_init: &heat-image hemsonawane/heat:latest-zed-ubuntu_focal
        glance_db_sync: *glance-image
        db_drop: *heat-image
        ks_user: *heat-image
        ks_service: *heat-image
        ks_endpoints: *heat-image
        rabbit_init: docker.io/rabbitmq:3.9-management
        glance_api: *glance-image
        # Bootstrap image requires curl
        bootstrap: *heat-image
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.io/docker:17.07.0
      pull_policy: Always
    endpoints:
      identity:
        auth:
          admin:
            password: grijgfreiefdf
          glance:
            password: 6ohpeyIbd95tqZyZD0Dz
          test:
            password: Kiz2K4elg3OygKtyU5QC
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek
          glance:
            password: YKY6KzpD7Y2166e7reTU
      oslo_cache:
        auth:
          memcache_secret_key: 4hvV8Q8ZBrQbguej4jwj
      oslo_messaging:
        auth:
          admin:
            username: rabbitmq-admin
            password: 5mOMtMEnkx4TxTwEMGqY
          glance:
            username: glance-rabbitmq-user
            password: NnCTmrCu0kZNQDyR3V9j
        statefulset:
          replicas: 3
          name: openstack-rabbitmq-rabbitmq
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      registry:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    #pod:
    #  replicas:
    #    api: 3
    #    registry: 2
    # NOTE(portdirect): glance APIv1 is required for heat in Newton
    conf:
      glance:
        DEFAULT:
          enable_v1_api: true
          show_multiple_locations: True
        glance_store:
          store: "file,http,swift,cinder"
    volume:
      class_name: ceph-block
