kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: libvirt
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "cinder"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: libvirt
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        libvirt: breton/poop2:latest
        ceph_config_helper: docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20220802
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.itera.io/docker:17.07.0
      pull_policy: Always
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      libvirt:
        listen_tcp: "1"
        listen_tls: "0"
        auth_tcp: "none"
        ca_file: ""
        listen_addr: "0.0.0.0"
        log_level: "3"
        log_outputs: "1:file:/var/log/libvirt/libvirtd.log"
