kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: placement
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "cinder"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: placement
      sourceRef:
        kind: GitRepository
        name: openstack-helm
        namespace: default 
      interval: 1m
  values:
    network:
      api:
        node_port:
          enabled: true
    endpoints:
      identity:
        name: keystone
        auth:
          admin:
            password: grijgfreiefdf 
          placement:
            username: placement
            password: SF3L4KakWlbj1naAjwTz 
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek 
          placement:
            username: nova
            password: 8yPTwBDaTaQzUvxVSAqT 
      oslo_cache:
        auth:
          memcache_secret_key: 4hvV8Q8ZBrQbguej4jwj
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        api: 3
    images:
      pull_policy: Always
      tags:
        placement: &placement-image hemsonawane/placement:latest-zed-ubuntu_focal
        ks_user: &heat-image hemsonawane/heat:latest-zed-ubuntu_focal
        ks_service: *heat-image
        ks_endpoints: *heat-image
        db_init: *heat-image
        db_drop: *heat-image
        db_migrate: "quay.io/airshipit/porthole-mysqlclient-utility:latest-ubuntu_bionic"
        placement_db_sync: *placement-image
        dep_check: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
        image_repo_sync: "docker.io/docker:17.07.0"
