kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: heat
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "openvswitch"
    namespace: "openstack"
  - name: "libvirt"
    namespace: "openstack"
  - name: "nova"
    namespace: "openstack"
  - name: "placement"
    namespace: "openstack"
  - name: "neutron"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: heat
      sourceRef:
        kind: GitRepository
        name: openstack-helm
        namespace: default 
      interval: 1m
  values:
    network:
      api:
        node_port:
          enabled: true 
      cfn:
        node_port:
          enabled: true 
    images:
      tags:
        test: docker.itera.io/xrally/xrally-openstack:2.0.0
        bootstrap: &heat-image hemsonawane/heat:latest-zed-ubuntu_focal
        db_init: *heat-image
        heat_db_sync: *heat-image
        db_drop: *heat-image
        rabbit_init: docker.io/rabbitmq:3.9-management
        ks_user: *heat-image
        ks_service: *heat-image
        ks_endpoints: *heat-image
        heat_api: *heat-image
        heat_cfn: *heat-image
        heat_cloudwatch: *heat-image
        heat_engine: *heat-image
        heat_engine_cleaner: *heat-image
        heat_purge_deleted: *heat-image
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.itera.io/docker:17.07.0
    endpoints:
      identity:
        auth:
          admin:
            password: grijgfreiefdf
          heat:
            password: UM30jUu5oVyLSN83pyDl
          heat_trustee:
            password: taBmZdSd0ygg8QUthJRm
          heat_stack_user:
            password: kAd1jjS8bXEdk1NPZBz7
          test:
            password: Se6TksJNulWX0JZWNFA3
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek
          heat:
            password: g3xIjv3JR5nRFIxGjrd0
      oslo_cache:
        hosts:
          default: heat-memcached
      oslo_messaging:
        auth:
          admin:
            username: rabbitmq-admin
            password: 5mOMtMEnkx4TxTwEMGqY
          heat:
            username: heat-rabbitmq-user
            password: tdB75UOZUWOTzbnKaHHb
        statefulset:
          replicas: 3
          name: openstack-rabbitmq-rabbitmq
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      cfn:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      cloudwatch:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      engine:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    #pod:
    #  replicas:
    #    api: 2
    #    cfn: 2
    #    cloudwatch: 2
    #    engine: 2
