kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: prometheus-openstack-exporter
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "barbican"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: prometheus-openstack-exporter
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    images:
      tags:
        prometheus_openstack_exporter: docker.io/openstackhelm/prometheus-openstack-exporter:latest-ubuntu_bionic
#        #prometheus_openstack_exporter: docker.itera.io/openstackhelm/prometheus-openstack-exporter:ubuntu_bionic-20191017
        dep_check: docker.itera.io/stackanetes/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.itera.io/docker:17.07.0
        ks_user: docker.itera.io/openstackhelm/heat:latest-victoria-ubuntu_bionic
    endpoints:
      identity:
        auth:
          admin:
            password: grijgfreiefdf
          user:
            password: vUThQioNVROZ7SDFRdxv
    labels:
      node_selector_key: openstack-control-plane
      node_selector_value: enabled
