kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: powerdns
  namespace: openstack
spec:
  interval: 5m
  dependsOn:
  - name: "designate"
    namespace: "openstack"
  targetNamespace: openstack
  storageNamespace: openstack
  chart:
    spec:
      chart: powerdns
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    network:
      node_port_enabled: true
      external_policy_local: true
    images:
      tags:
        powerdns: docker.io/psitrax/powerdns:latest
        db_init: docker.io/openstackhelm/heat:wallaby-ubuntu_focal
        db_sync: docker.io/psitrax/powerdns:latest
        dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        image_repo_sync: docker.io/library/docker:17.07.0
    endpoints:
      oslo_db:
        auth:
          admin:
            password: hQrCbbmZQqGJbfedePek
          powerdns:
            password: nhwpdARvtebFBSqXCfQLUx
    labels:
      powerdns:
        node_selector_key: openstack-control-plane-pdns
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane-pdns
        node_selector_value: enabled
      test:
        node_selector_key: openstack-control-plane-pdns
        node_selector_value: enabled

