apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openstack-helm
  namespace: default
spec:
  interval: 5m0s
  url: ssh://git@infra.itera.io/shubham/openstack-helm.git  #git@infra.itera.io/shubham/openstack-helm.git  #git@infra.itera.io/cedric-osh-lab/openstack-helm 
  ref:
    branch: master
  secretRef:
    name: podinfo-auth
