# Example of plain secret structure, avoid pushing plain secrets into Git, pre-commit hook / CI test needed
apiVersion: v1
stringData:
  mariadb.admin.password: '********************'
  mariadb.exporter.password: '********************'
  mariadb.sst.password: '********************'
  prometheus.endpoints.monitoring.auth.admin.password: '********************'
  grafana.endpoints.oslo_db.auth.user.password: '********************'
  grafana.endpoints.oslo_db_session.auth.user.password: '********************'
  grafana.endpoints.grafana.auth.admin.password: '********************'
  alertmanager.slack.channel.webhook.url: 'https://hooks.slack.com/services/*********/***********/************************'
  oauth2-proxy-prometheus.config.clientSecret: '0000000000000000000000000000000000000000000000000000000000000000'
  oauth2-proxy-prometheus.config.cookieSecret: '00000000000000000000000000000000'
  oauth2-proxy-alertmanager.config.clientSecret: '0000000000000000000000000000000000000000000000000000000000000000'
  oauth2-proxy-alertmanager.config.cookieSecret: '00000000000000000000000000000000'
  oauth2-proxy-grafana.config.clientSecret: '0000000000000000000000000000000000000000000000000000000000000000'
  oauth2-proxy-grafana.config.cookieSecret: '00000000000000000000000000000000'
kind: Secret
metadata:
  name: common
  namespace: osh-infra
type: Opaque
