kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: kube-state-metrics
  namespace: &ns osh-infra
spec:
  interval: 5m
  targetNamespace: *ns
  storageNamespace: *ns
  chart:
    spec:
      chart: prometheus-kube-state-metrics
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  values:
    labels:
      kube_state_metrics:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
