kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: grafana
  namespace: &ns osh-infra
spec:
  interval: 5m
  targetNamespace: *ns
  storageNamespace: *ns
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: GitRepository
        name: openstack-helm-infra
        namespace: default 
      interval: 1m
  valuesFrom:
  - kind: Secret
    name: common
    valuesKey: prometheus.endpoints.monitoring.auth.admin.password
    targetPath: endpoints.monitoring.auth.admin.password
  - kind: Secret
    name: common
    valuesKey: mariadb.admin.password
    targetPath: endpoints.oslo_db.auth.admin.password
  - kind: Secret
    name: common
    valuesKey: grafana.endpoints.oslo_db.auth.user.password
    targetPath: endpoints.oslo_db.auth.user.password
  - kind: Secret
    name: common
    valuesKey: mariadb.admin.password
    targetPath: endpoints.oslo_db_session.auth.admin.password
  - kind: Secret
    name: common
    valuesKey: grafana.endpoints.oslo_db_session.auth.user.password
    targetPath: endpoints.oslo_db_session.auth.user.password
  - kind: Secret
    name: common
    valuesKey: grafana.endpoints.grafana.auth.admin.password
    targetPath: endpoints.grafana.auth.admin.password
  values:
    images:
      tags:
        grafana: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/grafana__grafana:7.3.7-ubuntu
        dep_check: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.itera.io__stackanetes__kubernetes-entrypoint:v1.0.0
        db_init: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.itera.io__openstackhelm__heat:latest-wallaby-ubuntu_bionic
        grafana_db_session_sync: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.itera.io__openstackhelm__heat:latest-wallaby-ubuntu_bionic
        helm_tests: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.itera.io__openstackhelm__heat:latest-wallaby-ubuntu_bionic
        image_repo_sync: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.itera.io__docker:17.07.0
    manifests:
      ingress: false
      service_ingress: false
    network:
      grafana:
        node_port:
          enabled: true
          port: 30009
    endpoints:
      monitoring:
        auth:
          admin: {}
          #  password: secret/common/prometheus.endpoints.monitoring.auth.admin.password
      oslo_db:
        namespace: *ns
        auth:
          admin: {}
          #  password: secret/common/mariadb.admin.password
          user: {}
          #  password: secret/common/grafana.endpoints.oslo_db.auth.user.password
      oslo_db_session:
        namespace: *ns
        auth:
          admin: {}
          #  password: secret/common/mariadb.admin.password
          user: {}
          #  password: secret/common/grafana.endpoints.oslo_db_session.auth.user.password
      grafana:
        auth:
          admin: {}
          #  password: secret/common/grafana.endpoints.grafana.auth.admin.password
    labels:
      grafana:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    conf:
      grafana:
        auth.ldap:
          enabled: false
    pod:
      env:
        grafana:
          GF_USERS_AUTO_ASSIGN_ORG: "true"
          GF_USERS_AUTO_ASSIGN_ORG_ID: "1"
          GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Viewer"
          GF_USERS_LOGIN_HINT: "Login with cloud grafana admin credentials"
          GF_USERS_VIEWERS_CAN_EDIT: "true"
          GF_AUTH_PROXY_ENABLED: "true"
          GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
          GF_AUTH_PROXY_HEADER_NAME: "X-Auth-Request-Email"
          GF_AUTH_PROXY_HEADER_property: "email"
