apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 6m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  # Decryption configuration starts here
  decryption:
    provider: sops
    secretRef:
      name: sops-age-key-dev-beskar
