apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 00-common-configmap.yaml
  - 00-common-encryptedsecret.yaml
  - 01-egi-accounting.yaml
  - 02-egi-appliances.yaml
