#################################################################################################################
# Define the settings for the rook-ceph-external cluster with common settings for a production cluster.

# For example, if Rook is not managing any existing cluster in the 'rook-ceph' namespace do:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster-external.yaml

# If there is already a cluster managed by Rook in 'rook-ceph' then do:
#   kubectl create -f common-external.yaml
#   kubectl create -f cluster-external.yaml
#################################################################################################################
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
  namespace: rook-ceph-external # namespace:cluster
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  # external ceph version, should match external cluster version!
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.12
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: false
    externalMgrEndpoints:
    - ip: 78.1.2.240
    - ip: 78.1.2.241
    - ip: 78.1.2.242
