kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: horizon
  namespace: openstack
spec:
  values:
    network:
      dashboard:
        ingress:
          classes:
            namespace: "nginx"
            cluster: "nginx-cluster"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: "letsencrypt"
    endpoints:
      dashboard:
        port:
          api:
            public: 443
        scheme:
          public: https
        host_fqdn_override:
          public:
            host: horizon.shubham.taikun.services
            tls:
              dnsNames:
                - horizon.shubham.taikun.services
            issuerRef:
              name: letsencrypt
              kind: ClusterIssuer
