apiVersion: v1
kind: Secret
metadata:
    name: images-rbd-keyring
    namespace: openstack
type: kubernetes.io/rbd
stringData:
    key: ENC[AES256_GCM,data:r5pGtrQ6Xf15k90VZF+OfT2On09gnLxcEOsschJ+B/adSM91ws+s3A==,iv:7ne96Go9DastzGbD8rlhxPM/p9wL/eQYzC0CqTa+n4U=,tag:PmTd76thB1T1Nz+pSqRkhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv9468v9dcmzxksl4cmnny9pw679zh29cvc5u9fl42g6s0f4h9cq8yjzx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UWRWUVI2T1NnNTM0N09w
            RVU1elgzSGVnckhhWVN4NGN3OVAybGJNcFdzCktscXFKVHFacHF1dDlhOU1LbHRN
            SkxVTCtsOVRHSVlrVG5vYU90djhCeFUKLS0tIDVSSGZ6WG1uTVdyeG1NaWtNeU5N
            eVNOOTBHaVZ6L1FpNEhraU5pQzB3T2cKJUoxlRLyYJYbT0+n/loXWhxw6bXivJle
            PY7ZwbeD5Z/lAvb3XwlphQZYJ+7aYW735TM2aRpvrv01HVfqVcL2dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T09:20:03Z"
    mac: ENC[AES256_GCM,data:+rMd9CcaeNJzyPStz+027lTmkjZzMFhUJy3Zx4gWQBQhYV4hWTZSQx7ZLxMjDyZagvn0ujoBlIbcovErl6tjNndHE7KVla9hPcMeIhyE6IsMgJDqVLVJ9r7IiZyjrzSiJBObuNbIlufiM5R9y020YSd6o9Y7fhr0p4kMlQ8s7nY=,iv:3S5ktxLwDZcgKgqBDvaYqqiHi2vqTlqu25j8pTY4OCk=,tag:rVh4hQKRr4b7AgTdFsDNdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
