apiVersion: v1
kind: Secret
metadata:
    name: rgw-admin-ops-user
    namespace: rook-ceph-external
type: kubernetes.io/rook
stringData:
    accessKey: ""
    secretKey: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv9468v9dcmzxksl4cmnny9pw679zh29cvc5u9fl42g6s0f4h9cq8yjzx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRmxCVWljK083VXU4aU81
            SEFTbnNISk1OKy9uOWtGMDVJMXdoVHVJYmh3CnZET1FXVjYyMEh6Q2cyV3ZKeTJq
            Tk1QYk5WNnErVXl4NGFyUmIzaVNVaG8KLS0tIEJqTUFGRktQMWV3UlhoelBzZGFp
            OW1LODYxcmh6b2thMmdyRDl2RVJJZ1kK6XIR5DtoiUjGOMKcf9/Zx8eLKDV/8faS
            px5i3xHGScELtBiu4W/JqJ/qu/5LQoJ/K01hGtUlRJpHkBiMr8qX7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T08:39:18Z"
    mac: ENC[AES256_GCM,data:ISfmUr9DeoLJn1eyxxPAbd+wukhIyymxj1Y9dlgjGMzY9wBFizwubpepp48NVc3DOvr+aFq7kTMu7jYki7mMnounM/qeYm9tGBgFD8c8bRrg5QusLeuoyvTTeNfcTAKr6AM1+z3Y5W9yGXUKW7NRann6EeVNwMF4CqUSF92lceQ=,iv:ANDFkwEyMGSqivS8DUZza5+ViXTX+KxsVP+20OXOdrs=,tag:IvDQzmT5xoRJmA6Y5U5ptQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
